name: Sync to Bitbucket

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push
        uses: ./
        with:
          username: "eric.muir"
          password: ${{ secrets.BITBUCKET_PASSWORD }}